orbs:
  aws-eks: circleci/aws-eks@1.1.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-cli: circleci/aws-cli@3.1.0
  node: circleci/node@2.0.2
 
jobs:
  deploy-dev:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy-Dev.
          command: ssh ec2-user@16.170.149.164 './node-frontend-qa-ssh.sh';
 
version: 2.1
workflows:
  build_and_deploy-dev:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL_DEV
          aws-access-key-id: AWS_DEV_ACCESS_KEY
          aws-secret-access-key: AWS_DEV_SECRET_KEY
          # context: myContext
          create-repo: true
          dockerfile: Env/Dev/Dockerfile
          extra-build-args: "--build-arg BIT_TOKEN=$BIT_TOKEN --build-arg REACT_APP_TOKEN=$REACT_APP_TOKEN --build-arg REACT_APP_ENV=DEV --build-arg REACT_APP_EVENTS_LIMIT=1000  --build-arg REACT_APP_AUDIT_LIMIT=1000 "          
          no-output-timeout: 20m
          path: .
          ## profile-name: myProfileName
          region: AWS_REGION
          repo: nglc-portal-dev
          skip-when-tags-exist: false
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: anshika
      - deploy-dev:
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: anshika
